from interface_lancement_jeu import nom_carte

cartes_images = {
    "2 de carreau": "cards/2 de carreau.png",
    "2 de trefle": "cards/2 de trefle.png",
    "2 de coeur": "cards/2 de coeur.png",
    "2 de pique": "cards/2 de pique.png",
    "3 de carreau": "cards/3 de carreau.png",
    "4 de carreau": "cards/4 de carreau.png",                                                                
    "5 de carreau": "cards/5 de carreau.png",                                             
    "6 de carreau": "cards/6 de carreau.png",
    "7 de carreau": "cards/7 de carreau.png",
    "8 de carreau": "cards/8 de carreau.png",
    "9 de carreau": "cards/9 de carreau.png",
    "10 de carreau": "cards/10 de carreau.png",
    "valet de carreau": "cards/valet de carreau.png",
    "dame de carreau": "cards/dame de carreau.png",
    "roi de carreau": "cards/roi de carreau.png",
    "as de carreau": "cards/as de carreau.png",
    "3 de trefle": "cards/3 de trefle.png",
    "4 de trefle": "cards/4 de trefle.png",
    "5 de trefle": "cards/5 de trefle.png",
    "6 de trefle": "cards/6 de trefle.png",
    "7 de trefle": "cards/7 de trefle.png",
    "8 de trefle": "cards/8 de trefle.png",
    "9 de trefle": "cards/9 de trefle.png",
    "10 de trefle": "cards/10 de trefle.png",
    "valet de trefle": "cards/valet de trefle.png",
    "dame de trefle": "cards/dame de trefle.png",
    "roi de trefle": "cards/roi de trefle.png",
    "as de coeur": "cards/as de trefle.png",
    "3 de coeur": "cards/3 de coeur.png",
    "4 de coeur": "cards/4 de coeur.png",
    "5 de coeur": "cards/5 de coeur.png",
    "6 de coeur": "cards/6 de coeur.png",
    "7 de coeur": "cards/7 de coeur.png",
    "8 de coeur": "cards/8 de coeur.png",
    "9 de coeur": "cards/9 de coeur.png",
    "10 de coeur": "cards/10 de coeur.png",
    "valet de coeur": "cards/valet de coeur.png",
    "dame de coeur": "cards/dame de coeur.png",
    "roi de coeur": "cards/roi de coeur.png",
    "as de coeur": "cards/as de coeur.png",
    "3 de pique": "cards/3 de pique.png",
    "4 de pique": "cards/4 de pique.png",
    "5 de pique": "cards/5 de pique.png",
    "6 de pique": "cards/6 de pique.png",
    "7 de pique": "cards/7 de pique.png",
    "8 de pique": "cards/8 de pique.png",
    "9 de pique": "cards/9 de pique.png",
    "10 de pique": "cards/10 de pique.png",
    "valet de pique": "cards/valet de pique.png",
    "dame de pique": "cards/dame de pique.png",
    "roi de pique": "cards/roi de pique.png",
    "as de pique": "cards/as de pique.png",
}

def label_image():
    global 
    try :
        chemin = f"cards/{}"